/* Robot.java */
/* Generated By:JavaCC: Do not edit this line. Robot.java */
package uniandes.lym.robot.control;

import uniandes.lym.robot.kernel.*;
import uniandes.lym.robot.view.Console;

import java.awt.Point;
import java.io.*;
import java.util.Vector;
import java.util.LinkedList;
import java.util.HashMap;
import java.util.ArrayList;
import java.util.List;

@SuppressWarnings("serial")
public class Robot implements RobotConstants {
        private RobotWorldDec world;
        private HashMap<String, Integer> variables = new HashMap<>();
        private HashMap<String, Procedure> procedures = new HashMap<>();

        void setWorld(RobotWorld w) {
                world = (RobotWorldDec) w;
        }

        String salida = new String();

        class Procedure {
                String name;
                List<String> parameters;
                List<String> body;

                Procedure(String name, List<String> parameters, List<String> body) {
                        this.name = name;
                        this.parameters = parameters;
                        this.body = body;
                }
        }

  final public boolean command(Console sistema) throws ParseException {int x, y, n;
        salida = new String();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MOVE:
    case TURN:
    case FACE:
    case PUT:
    case PICK:
    case POP:
    case GOTO:
    case JUMP:
    case NOP:
    case PROC:
    case IF:
    case WHILE:
    case REPEAT:
    case ID:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MOVE:{
        jj_consume_token(MOVE);
        jj_consume_token(38);
        x = expr();
        jj_consume_token(39);
world.moveForward(x, false); salida = "Command: Move";
        break;
        }
      case TURN:{
        jj_consume_token(TURN);
        jj_consume_token(38);
        direction();
        jj_consume_token(39);
world.turn(token.image); salida = "Command: Turn";
        break;
        }
      case FACE:{
        jj_consume_token(FACE);
        jj_consume_token(38);
        direction();
        jj_consume_token(39);
world.face(token.image); salida = "Command: Face";
        break;
        }
      case PUT:{
        jj_consume_token(PUT);
        jj_consume_token(38);
        n = expr();
        jj_consume_token(40);
        objType();
        jj_consume_token(39);
world.put(n, token.image); salida = "Command: Put";
        break;
        }
      case PICK:{
        jj_consume_token(PICK);
        jj_consume_token(38);
        n = expr();
        jj_consume_token(40);
        objType();
        jj_consume_token(39);
world.pick(n, token.image); salida = "Command: Pick";
        break;
        }
      case POP:{
        jj_consume_token(POP);
        jj_consume_token(38);
        n = expr();
        jj_consume_token(39);
world.popBalloons(n); salida = "Command: Pop";
        break;
        }
      case GOTO:{
        jj_consume_token(GOTO);
        jj_consume_token(38);
        x = expr();
        jj_consume_token(41);
        y = expr();
        jj_consume_token(39);
world.setPosition(x, y); salida = "Command: GoTo";
        break;
        }
      case JUMP:{
        jj_consume_token(JUMP);
        jj_consume_token(38);
        n = expr();
        jj_consume_token(42);
        direction();
        jj_consume_token(39);
world.jump(n, token.image); salida = "Command: Jump";
        break;
        }
      case NOP:{
        jj_consume_token(NOP);
        jj_consume_token(39);
salida = "Command: NOP";
        break;
        }
      case PROC:{
        procedure();
        break;
        }
      case ID:{
        variable_declaration();
        break;
        }{
        assignment();
        break;
        }
      case IF:{
        conditional();
        break;
        }
      case WHILE:
      case REPEAT:{
        loop();
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
try {
                        Thread.sleep(900);
                } catch (InterruptedException e) {
                        System.err.format("IOException: %s%n", e);
                }

                sistema.printOutput(salida);
                {if ("" != null) return true;}
      break;
      }
    case 0:{
      jj_consume_token(0);
{if ("" != null) return false;}
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public void procedure() throws ParseException {String procName;
        List<String> params = new ArrayList<>();
        List<String> body = new ArrayList<>();
    jj_consume_token(PROC);
    procName = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 43:{
      jj_consume_token(43);
      paramList();
      jj_consume_token(44);
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    jj_consume_token(43);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 0:
      case MOVE:
      case TURN:
      case FACE:
      case PUT:
      case PICK:
      case POP:
      case GOTO:
      case JUMP:
      case NOP:
      case PROC:
      case IF:
      case WHILE:
      case REPEAT:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        break label_1;
      }
      command();
    }
    jj_consume_token(44);
procedures.put(procName, new Procedure(procName, params, body));
}

  final public void paramList() throws ParseException {String param;
    param = jj_consume_token(ID);
params.add(param);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 45:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_2;
      }
      jj_consume_token(45);
      param = jj_consume_token(ID);
params.add(param);
    }
}

  final public void direction() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NORTH:{
      jj_consume_token(NORTH);
      break;
      }
    case SOUTH:{
      jj_consume_token(SOUTH);
      break;
      }
    case EAST:{
      jj_consume_token(EAST);
      break;
      }
    case WEST:{
      jj_consume_token(WEST);
      break;
      }
    case LEFT:{
      jj_consume_token(LEFT);
      break;
      }
    case RIGHT:{
      jj_consume_token(RIGHT);
      break;
      }
    case AROUND:{
      jj_consume_token(AROUND);
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void objType() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case BALLOONS:{
      jj_consume_token(BALLOONS);
      break;
      }
    case CHIPS:{
      jj_consume_token(CHIPS);
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void variable_declaration() throws ParseException {
    jj_consume_token(ID);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 46:{
        ;
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        break label_3;
      }
      jj_consume_token(46);
      jj_consume_token(ID);
    }
    jj_consume_token(ASSIGN);
    expr();
    jj_consume_token(39);
}

  final public void assignment() throws ParseException {
    jj_consume_token(ID);
    jj_consume_token(ASSIGN);
    expr();
    jj_consume_token(39);
}

  final public void conditional() throws ParseException {
    jj_consume_token(IF);
    expr();
    jj_consume_token(THEN);
    jj_consume_token(43);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 0:
      case MOVE:
      case TURN:
      case FACE:
      case PUT:
      case PICK:
      case POP:
      case GOTO:
      case JUMP:
      case NOP:
      case PROC:
      case IF:
      case WHILE:
      case REPEAT:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        break label_4;
      }
      command();
    }
    jj_consume_token(44);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
      jj_consume_token(ELSE);
      jj_consume_token(43);
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 0:
        case MOVE:
        case TURN:
        case FACE:
        case PUT:
        case PICK:
        case POP:
        case GOTO:
        case JUMP:
        case NOP:
        case PROC:
        case IF:
        case WHILE:
        case REPEAT:
        case ID:{
          ;
          break;
          }
        default:
          jj_la1[9] = jj_gen;
          break label_5;
        }
        command();
      }
      jj_consume_token(44);
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      ;
    }
}

  final public void loop() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case WHILE:{
      jj_consume_token(WHILE);
      expr();
      jj_consume_token(DO);
      jj_consume_token(43);
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 0:
        case MOVE:
        case TURN:
        case FACE:
        case PUT:
        case PICK:
        case POP:
        case GOTO:
        case JUMP:
        case NOP:
        case PROC:
        case IF:
        case WHILE:
        case REPEAT:
        case ID:{
          ;
          break;
          }
        default:
          jj_la1[11] = jj_gen;
          break label_6;
        }
        command();
      }
      jj_consume_token(44);
      break;
      }
    case REPEAT:{
      jj_consume_token(REPEAT);
      expr();
      jj_consume_token(REPEAT_BLOCK);
      jj_consume_token(43);
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 0:
        case MOVE:
        case TURN:
        case FACE:
        case PUT:
        case PICK:
        case POP:
        case GOTO:
        case JUMP:
        case NOP:
        case PROC:
        case IF:
        case WHILE:
        case REPEAT:
        case ID:{
          ;
          break;
          }
        default:
          jj_la1[12] = jj_gen;
          break label_7;
        }
        command();
      }
      jj_consume_token(44);
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public int expr() throws ParseException {int total = 1;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUM:{
      jj_consume_token(NUM);
total = Integer.parseInt(token.image);
      break;
      }
    case ID:{
      jj_consume_token(ID);
if (!variables.containsKey(token.image)) {if (true) throw new Error("Variable no definida: " + token.image);} total = variables.get(token.image);
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return total;}
    throw new Error("Missing return statement in function");
}

  /** Generated Token Manager. */
  public RobotTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[15];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x4a5ff80,0x4a5ff81,0x0,0x4a5ff81,0x0,0xc0000000,0x30000000,0x0,0x4a5ff81,0x4a5ff81,0x100000,0x4a5ff81,0x4a5ff81,0xa00000,0x4000000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0x800,0x0,0x2000,0x1f,0x0,0x4000,0x0,0x0,0x0,0x0,0x0,0x0,0x20,};
	}

  /** Constructor with InputStream. */
  public Robot(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Robot(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new RobotTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Robot(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new RobotTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new RobotTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Robot(RobotTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(RobotTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[47];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 15; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 47; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
