/* Robot.java */
/* Generated By:JavaCC: Do not edit this line. Robot.java */
package uniandes.lym.robot.control;

import uniandes.lym.robot.kernel.*;
import uniandes.lym.robot.view.Console;

import java.awt.Point;
import java.io.*;
import java.util.Vector;
import java.util.LinkedList;
import java.util.HashMap;
import java.util.ArrayList;
import java.util.List;

@SuppressWarnings("serial")
public class Robot implements RobotConstants {
        private RobotWorldDec world;
        private HashMap<String, Integer> variables = new HashMap<>();
        private HashMap<String, Procedure> procedures = new HashMap<>();

        void setWorld(RobotWorld w) {
                world = (RobotWorldDec) w;
        }

        String salida = new String();

        class Procedure {
                String name;
                HashMap<String, Integer> paramValues;
                List<String> paramNames;
                HashMap<String, Integer> varLocales = new HashMap<>();
                List<String> body;

                Procedure(String name, HashMap<String, Integer> paramValues, List<String> paramNames, List<String> body)
                {
                        this.name = name;
                        this.paramNames = paramNames;
                        this.body = body;
                        this.paramValues = paramValues;
                }
        }

  final public Token objType() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case BALLOONS:{
      t = jj_consume_token(BALLOONS);
{if ("" != null) return t;}
      break;
      }
    case CHIPS:{
      t = jj_consume_token(CHIPS);
{if ("" != null) return t;}
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public boolean command(Console sistema) throws ParseException {boolean bool;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 55:{
      variable_declaration(true, "");
bool=true;
        {if ("" != null) return bool;}
      break;
      }
    case 0:
    case MOVE:
    case TURN:
    case FACE:
    case PUT:
    case PICK:
    case GOTO:
    case JUMP:
    case NOP:
    case PROC:
    case IF:
    case WHILE:
    case FOR:
    case ID:{
      bool = interna(sistema, true, 1, "");
{if ("" != null) return bool;}
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public boolean interna(Console sistema, boolean ejecutar, int numVecesEjecucion, String procName) throws ParseException {int x, y, n;
    salida = new String();
    Token t;
    Token tok;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MOVE:
    case TURN:
    case FACE:
    case PUT:
    case PICK:
    case GOTO:
    case JUMP:
    case NOP:
    case PROC:
    case IF:
    case WHILE:
    case FOR:
    case ID:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MOVE:{
        jj_consume_token(MOVE);
        jj_consume_token(52);
        x = expr(procName);
        moveIndirTothe(x, ejecutar, numVecesEjecucion, procName);
        jj_consume_token(53);
salida = "Command: Move";
        break;
        }
      case TURN:{
        jj_consume_token(TURN);
        jj_consume_token(52);
        turnDirections(ejecutar,numVecesEjecucion, procName);
        jj_consume_token(53);
salida = "Command: Turn";
        break;
        }
      case FACE:{
        jj_consume_token(FACE);
        jj_consume_token(52);
        faceDirections(ejecutar,numVecesEjecucion, procName);
        jj_consume_token(53);
salida = "Command: Face";
        break;
        }
      case PUT:{
        jj_consume_token(PUT);
        jj_consume_token(52);
        n = expr(procName);
        jj_consume_token(OFTYPE);
        t = objType();
        jj_consume_token(53);
if (ejecutar)
                { for (int i = 0; i < numVecesEjecucion; i++)
                  {
                        if (n <= 0) {if (true) throw new Error("PUT error: n debe ser mayor que 0");}
                        if (t.image.equals("#chips")) {
                            world.putChips(n);
                            salida = "Command: Put " + n + " chips";
                        }
                        else if (t.image.equals("#balloons"))
                        {
                            world.putBalloons(n);
                            salida = "Command: Put " + n + " balloons";
                         }
                          }
                }
        break;
        }
      case PICK:{
        jj_consume_token(PICK);
        jj_consume_token(52);
        n = expr(procName);
        jj_consume_token(OFTYPE);
        t = objType();
        jj_consume_token(53);
if (ejecutar)
              { for (int i = 0; i < numVecesEjecucion; i++)
                {
                        if (n <= 0) {if (true) throw new Error("PICK error: n debe ser mayor que 0");}
                        if (t.image.equals("#chips")) {
                            world.pickChips(n);
                            salida = "Command: Pick " + n + " chips";
                        } else if (t.image.equals("#balloons")) {
                            world.grabBalloons(n);
                            salida = "Command: Pick " + n + " balloons";
                        }
                     }
                   }
        break;
        }
      case GOTO:{
        jj_consume_token(GOTO);
        jj_consume_token(52);
        x = expr(procName);
        jj_consume_token(54);
        y = expr(procName);
        jj_consume_token(53);
if (ejecutar)
                        { for (int i = 0; i < numVecesEjecucion; i++)
                                {  world.setPostion(x, y); salida = "Command: GoTo"; }
                        }
        break;
        }
      case JUMP:{
        jj_consume_token(JUMP);
        jj_consume_token(52);
        n = expr(procName);
        jumpIndirTothe(n, ejecutar, numVecesEjecucion, procName);
        jj_consume_token(53);
salida = "Command: Jump";
        break;
        }
      case NOP:{
        jj_consume_token(NOP);
        jj_consume_token(53);
salida = "Command: NOP";
        break;
        }
      case PROC:{
        procedure(sistema);
        break;
        }
      case ID:{
        idTokenPath(procName);
        break;
        }
      case IF:{
        conditional(sistema, procName);
        break;
        }
      case WHILE:
      case FOR:{
        loop(sistema, procName);
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
try { Thread.sleep(900); }
        catch (InterruptedException e) { System.err.format("IOException: %s%n", e); }

        sistema.printOutput(salida);
        {if ("" != null) return true;}
      break;
      }
    case 0:{
      jj_consume_token(0);
{if ("" != null) return false;}
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public void variable_declaration(boolean esGlobal, String procName) throws ParseException {Token varName;
    jj_consume_token(55);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_1;
      }
      varName = jj_consume_token(ID);
if (esGlobal) {
              variables.put(varName.image, 0);
          }
          else
                procedures.get(procName).varLocales.put(varName.image, 0);
    }
    jj_consume_token(55);
}

  final public void assignment(Token varName, String procName) throws ParseException {int valor;
    jj_consume_token(ASSIGN);
    valor = expr(procName);
    jj_consume_token(53);
if (variables.containsKey(varName.image)) {
            // Si es una variable global, actualiza su valor
            variables.put(varName.image, valor);
        }
        else if (procedures.containsKey(procName) && procedures.get(procName).paramValues.containsKey(varName.image))
        {
                //Caso de que es un parametro
                procedures.get(procName).paramValues.put(varName.image, valor);
        }
        else if (procedures.containsKey(procName) && procedures.get(procName).varLocales.containsKey(varName.image))
        {
          //Caso de que es una variable local
          procedures.get(procName).varLocales.put(varName.image, valor);
       }
        else
        {
            {if (true) throw new Error("Variable no definida: " + varName.image);}
        }
}

  final public void procedure(Console sistema) throws ParseException {Token procName;
    List<String> body = new ArrayList<>();
    HashMap<String, Integer > paramValues = new HashMap<String, Integer >();
    List<String > paramNames = new ArrayList<>();
    jj_consume_token(PROC);
    procName = jj_consume_token(ID);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 52:{
        ;
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        break label_2;
      }
      jj_consume_token(52);
      paramList(paramValues, paramNames);
    }
    jj_consume_token(56);
procedures.put(procName.image, new Procedure(procName.image, paramValues, paramNames, body));
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 55:{
      variable_declaration(false, procName.image);
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 0:
      case MOVE:
      case TURN:
      case FACE:
      case PUT:
      case PICK:
      case GOTO:
      case JUMP:
      case NOP:
      case PROC:
      case IF:
      case WHILE:
      case FOR:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        break label_3;
      }
      interna(sistema, false, 1, procName.image);
    }
    jj_consume_token(57);
}

  final public void paramList(HashMap<String, Integer > paramValues, List<String> paramNames) throws ParseException {Token param;
    param = jj_consume_token(ID);
paramValues.put(param.image, 0);
                  paramNames.add(param.image);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ID:
      case 54:{
        ;
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        break label_4;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ID:{
        jj_consume_token(ID);
        jj_consume_token(52);
        break;
        }
      case 54:{
        jj_consume_token(54);
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      param = jj_consume_token(ID);
paramValues.put(param.image, 0);
                  paramNames.add(param.image);
    }
}

  final public void idTokenPath(String procName) throws ParseException {Token tok;
    tok = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ASSIGN:{
      assignment(tok, procName);
      break;
      }
    case 52:
    case 53:{
      procCall(tok, procName);
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void procCall(Token procTok, String procName) throws ParseException {int numParam=0;
  Procedure proc;
  int n;
  Token tok;
  String paramName;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 52:{
      jj_consume_token(52);
      n = expr(procName);
if (!procedures.containsKey(procTok.image))
                        {if (true) throw new Error("No esta definido  el procedimiento " + procTok );}
                else
                        proc=procedures.get(procTok.image);

                if (proc.paramNames.size()< 1)
                        {if (true) throw new Error("Numero incorrecto de parametros");}

                 numParam=1;
         paramName=proc.paramNames.get(0);
         proc.paramValues.put(paramName, n);
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ID:{
          ;
          break;
          }
        default:
          jj_la1[11] = jj_gen;
          break label_5;
        }
        jj_consume_token(ID);
        jj_consume_token(52);
        n = expr(procName);
numParam+=1;

                 if (proc.paramNames.size()< numParam)
                        {if (true) throw new Error("Numero incorrecto de parametros para este procedimiento");}

         paramName=proc.paramNames.get(numParam-1);
         proc.paramValues.put(paramName, n);
      }
      jj_consume_token(53);
procBodyCommands(procTok.image);
      break;
      }
    case 53:{
      jj_consume_token(53);
if (!procedures.containsKey(procTok.image))
                        {if (true) throw new Error("No esta definido  el procedimiento " + procTok );}
                  else
                        procBodyCommands(procTok.image);
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

///
///MOVE Y JUMP COMMANDS
///
  final public void moveDirectionLRFB(int x, boolean ejecutar, int numVeces, String procName) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LEFT:{
      jj_consume_token(LEFT);
if (ejecutar)
                { for (int i = 0; i < numVeces; i++)
                        { instrMoveJumpLeft(x, false); }
                        }
                        if (procedures.containsKey(procName) ){
                        Procedure proc= procedures.get(procName);
                        proc.body.add("move left_"+String.valueOf(x)); }
      break;
      }
    case RIGHT:{
      jj_consume_token(RIGHT);
if (ejecutar)
                { for (int i = 0; i < numVeces; i++)
                        { instrMoveJumpRight(x, false);}
                        }
                        if (procedures.containsKey(procName) ){
                        Procedure proc= procedures.get(procName);
                        proc.body.add("move right_"+String.valueOf(x));}
      break;
      }
    case FRONT:{
      jj_consume_token(FRONT);
if (ejecutar)
                { for (int i = 0; i < numVeces; i++)
                        { world.moveForward(x, false) ; }
                }
                if (procedures.containsKey(procName) ){
                        Procedure proc= procedures.get(procName);
                        proc.body.add("move forward_"+String.valueOf(x)); }
      break;
      }
    case BACK:{
      jj_consume_token(BACK);
if (ejecutar)
                { for (int i = 0; i < numVeces; i++)
                        { instrMoveJumpBack(x,false); }
                        }
                        if (procedures.containsKey(procName) ){
                        Procedure proc= procedures.get(procName);
                        proc.body.add("move back_"+String.valueOf(x)); }
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void moveDirectionNESW(int x, boolean ejecutar, int numVeces, String procName) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case EAST:{
      jj_consume_token(EAST);
if (ejecutar)
                                { for (int i = 0; i < numVeces; i++)
                                        { instrMoveEast(x); }
                                }
                                if (procedures.containsKey(procName) ){
                                Procedure proc= procedures.get(procName);
                                proc.body.add("move east_"+String.valueOf(x)); }
      break;
      }
    case WEST:{
      jj_consume_token(WEST);
if (ejecutar)
                                { for (int i = 0; i < numVeces; i++)
                                        { instrMoveWest(x); }
                                }
                                if (procedures.containsKey(procName) ){
                                Procedure proc= procedures.get(procName);
                                proc.body.add("move west_"+String.valueOf(x)); }
      break;
      }
    case NORTH:{
      jj_consume_token(NORTH);
if (ejecutar)
                                { for (int i = 0; i < numVeces; i++)
                                        {  instrMoveNorth(x);}
                                }
                                if (procedures.containsKey(procName) ){
                                Procedure proc= procedures.get(procName);
                                proc.body.add("move north_"+String.valueOf(x)); }
      break;
      }
    case SOUTH:{
      jj_consume_token(SOUTH);
if (ejecutar)
                                { for (int i = 0; i < numVeces; i++)
                                        {  instrMoveSouth(x);}
                                }
                                if (procedures.containsKey(procName) ){
                                Procedure proc= procedures.get(procName);
                                proc.body.add("move south_"+String.valueOf(x)); }
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void moveIndirTothe(int x, boolean ejecutar, int numVeces, String procName) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INDIR:{
      jj_consume_token(INDIR);
      moveDirectionNESW(x, ejecutar, numVeces, procName);
      break;
      }
    case TOTHE:{
      jj_consume_token(TOTHE);
      moveDirectionLRFB(x, ejecutar, numVeces, procName);
      break;
      }
    default:
      jj_la1[15] = jj_gen;
if (ejecutar)
                { for (int i = 0; i < numVeces; i++)
                        {world.moveForward(x, false); }
                }
                if (procedures.containsKey(procName) ){
                Procedure proc= procedures.get(procName);
                proc.body.add("move forward_"+String.valueOf(x)); }
    }
}

  final public void jumpIndirTothe(int x, boolean ejecutar, int numVeces, String procName) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INDIR:{
      jj_consume_token(INDIR);
      jumpDirectionNESW(x,ejecutar, numVeces, procName);
      break;
      }
    case TOTHE:{
      jj_consume_token(TOTHE);
      jumpDirectionLRFB(x,ejecutar, numVeces, procName);
      break;
      }
    default:
      jj_la1[16] = jj_gen;
if (ejecutar)
                { for (int i = 0; i < numVeces; i++)
                        {world.moveForward(x, true); }
                }
                if (procedures.containsKey(procName) ){
                Procedure proc= procedures.get(procName);
                proc.body.add("jump forward_"+String.valueOf(x)); }
    }
}

  final public void jumpDirectionNESW(int x, boolean ejecutar, int numVeces, String procName) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case EAST:{
      jj_consume_token(EAST);
if (ejecutar)
                        { for (int i = 0; i < numVeces; i++)
                                { instrJumpEast(x); }
                        }
                        if (procedures.containsKey(procName) ){
                        Procedure proc= procedures.get(procName);
                        proc.body.add("jump east_"+String.valueOf(x)); }
      break;
      }
    case WEST:{
      jj_consume_token(WEST);
if (ejecutar)
                                { for (int i = 0; i < numVeces; i++)
                                        { instrJumpWest(x); }
                                }
                        if (procedures.containsKey(procName) ){
                        Procedure proc= procedures.get(procName);
                        proc.body.add("jump west_"+String.valueOf(x)); }
      break;
      }
    case NORTH:{
      jj_consume_token(NORTH);
if (ejecutar)
                                { for (int i = 0; i < numVeces; i++)
                                        { instrJumpNorth(x); }
                                }
                                if (procedures.containsKey(procName) ){
                        Procedure proc= procedures.get(procName);
                        proc.body.add("jump north_"+String.valueOf(x)); }
      break;
      }
    case SOUTH:{
      jj_consume_token(SOUTH);
if (ejecutar)
                                { for (int i = 0; i < numVeces; i++)
                                        {  instrJumpSouth(x);}
                                }
                                if (procedures.containsKey(procName) ){
                        Procedure proc= procedures.get(procName);
                        proc.body.add("jump south_"+String.valueOf(x)); }
      break;
      }
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void jumpDirectionLRFB(int x, boolean ejecutar, int numVeces, String procName) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LEFT:{
      jj_consume_token(LEFT);
if (ejecutar)
                { for (int i = 0; i < numVeces; i++)
                        { instrMoveJumpLeft(x, true); }
                    }
                    if (procedures.containsKey(procName) ){
                        Procedure proc= procedures.get(procName);
                        proc.body.add("jump left_"+String.valueOf(x)); }
      break;
      }
    case RIGHT:{
      jj_consume_token(RIGHT);
if (ejecutar)
                { for (int i = 0; i < numVeces; i++)
                        { instrMoveJumpRight(x, true); }
                    }
                    if (procedures.containsKey(procName) ){
                        Procedure proc= procedures.get(procName);
                        proc.body.add("jump right_"+String.valueOf(x)); }
      break;
      }
    case FRONT:{
      jj_consume_token(FRONT);
if (ejecutar)
                { for (int i = 0; i < numVeces; i++)
                        { world.moveForward(x, true) ; }
                }
                if (procedures.containsKey(procName) ){
                        Procedure proc= procedures.get(procName);
                        proc.body.add("jump forward_"+String.valueOf(x)); }
      break;
      }
    case BACK:{
      jj_consume_token(BACK);
if (ejecutar)
                { for (int i = 0; i < numVeces; i++)
                        { instrMoveJumpBack(x, true); }
                    }
                    if (procedures.containsKey(procName) ){
                        Procedure proc= procedures.get(procName);
                        proc.body.add("jump back_"+String.valueOf(x)); }
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

///
//CONDITIONS Y LOOPS
//
  final public void conditional(Console sistema, String procName) throws ParseException {boolean bool;
  int numNot=0;
  boolean ejecutableIf=true;
  boolean ejecutableThen=false;
    jj_consume_token(IF);
    numNot = notCondition();
    bool = conditions(procName);
if (numNot%2!=0)
                bool=!bool;
          if (bool)
                { ejecutableIf= true;
                        ejecutableThen=false;
                        }
                else
                        { ejecutableIf=false;
                        ejecutableThen=true;
                        }
    jj_consume_token(THEN);
    jj_consume_token(56);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 0:
      case MOVE:
      case TURN:
      case FACE:
      case PUT:
      case PICK:
      case GOTO:
      case JUMP:
      case NOP:
      case PROC:
      case IF:
      case WHILE:
      case FOR:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        break label_6;
      }
      interna(sistema, ejecutableIf, 1, procName);
    }
    jj_consume_token(57);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
      jj_consume_token(ELSE);
      jj_consume_token(56);
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 0:
        case MOVE:
        case TURN:
        case FACE:
        case PUT:
        case PICK:
        case GOTO:
        case JUMP:
        case NOP:
        case PROC:
        case IF:
        case WHILE:
        case FOR:
        case ID:{
          ;
          break;
          }
        default:
          jj_la1[20] = jj_gen;
          break label_7;
        }
        interna(sistema, ejecutableThen, 1, procName);
      }
      jj_consume_token(57);
      break;
      }
    default:
      jj_la1[21] = jj_gen;
      ;
    }
}

  final public void loop(Console sistema, String procName) throws ParseException {boolean bool;
    int numNot = 0;
    boolean ejecutable;
    int repeticiones;
    int n;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case WHILE:{
      jj_consume_token(WHILE);
      numNot = notCondition();
      bool = conditions(procName);
if (numNot % 2 != 0) {
            bool = !bool;
        }
        ejecutable = bool;
      jj_consume_token(DO);
      jj_consume_token(56);
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 0:
        case MOVE:
        case TURN:
        case FACE:
        case PUT:
        case PICK:
        case GOTO:
        case JUMP:
        case NOP:
        case PROC:
        case IF:
        case WHILE:
        case FOR:
        case ID:{
          ;
          break;
          }
        default:
          jj_la1[22] = jj_gen;
          break label_8;
        }
        interna(sistema, ejecutable, 1, procName);
      }
      jj_consume_token(57);
      break;
      }
    case FOR:{
      jj_consume_token(FOR);
      n = expr(procName);
      jj_consume_token(REPEAT);
      jj_consume_token(56);
      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 0:
        case MOVE:
        case TURN:
        case FACE:
        case PUT:
        case PICK:
        case GOTO:
        case JUMP:
        case NOP:
        case PROC:
        case IF:
        case WHILE:
        case FOR:
        case ID:{
          ;
          break;
          }
        default:
          jj_la1[23] = jj_gen;
          break label_9;
        }
        interna(sistema, true, n, procName);
      }
      jj_consume_token(57);
      break;
      }
    default:
      jj_la1[24] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public int notCondition() throws ParseException {int total=0;
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NOT:{
        ;
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        break label_10;
      }
      jj_consume_token(NOT);
total+=1;
    }
{if ("" != null) return total;}
    throw new Error("Missing return statement in function");
}

  final public boolean conditions(String procname) throws ParseException {int x=0;
  boolean bool;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case CANMOVE:{
      jj_consume_token(CANMOVE);
      x = expr(procname);
      bool = canMoveInDirToTheCondition(x);
      jj_consume_token(53);
{if ("" != null) return bool;}
      break;
      }
    case FACING:{
      jj_consume_token(FACING);
      bool = facingCondition();
      jj_consume_token(53);
{if ("" != null) return bool;}
      break;
      }
    case CANPUT:{
      jj_consume_token(CANPUT);
      x = expr(procname);
      jj_consume_token(OFTYPE);
      bool = canPutCondition(x);
      jj_consume_token(53);
{if ("" != null) return bool;}
      break;
      }
    case CANPICK:{
      jj_consume_token(CANPICK);
      x = expr(procname);
      jj_consume_token(OFTYPE);
      bool = canPickCondition(x);
      jj_consume_token(53);
{if ("" != null) return bool;}
      break;
      }
    case CANJUMP:{
      jj_consume_token(CANJUMP);
      x = expr(procname);
      bool = canJumpInDirToTheCondition(x);
      jj_consume_token(53);
{if ("" != null) return bool;}
      break;
      }
    default:
      jj_la1[26] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public boolean canJumpInDirToTheCondition(int x) throws ParseException {boolean bool;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INDIR:{
      jj_consume_token(INDIR);
      bool = canJumpNESWCondition(x);
{if ("" != null) return bool;}
      break;
      }
    case TOTHE:{
      jj_consume_token(TOTHE);
      bool = canJumpLRFBCondition(x);
{if ("" != null) return bool;}
      break;
      }
    default:
      jj_la1[27] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public boolean canJumpNESWCondition(int steps) throws ParseException {Point pos;
  int newY;
  int newX;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SOUTH:{
      jj_consume_token(SOUTH);
pos=world.getPosition();
                  newY=pos.y+steps;
                  if (newY > world.getN() ||  world.isBlocked(new Point(pos.x, newY)))
                        {if ("" != null) return false;}
                  else
                        {if ("" != null) return true;}
      break;
      }
    case NORTH:{
      jj_consume_token(NORTH);
pos=world.getPosition();
                  newY=pos.y- steps;
                  if (newY< 1 || world.isBlocked(new Point(pos.x, newY)))
                        {if ("" != null) return false;}
                  else
                        {if ("" != null) return true;}
      break;
      }
    case EAST:{
      jj_consume_token(EAST);
pos=world.getPosition();
                  newX=pos.x+ steps;
                  if (newX > world.getN() || world.isBlocked(new Point(newX, pos.y)))
                        {if ("" != null) return false;}
                  else
                        {if ("" != null) return true;}
      break;
      }
    case WEST:{
      jj_consume_token(WEST);
pos=world.getPosition();
                  newX=pos.x- steps;
                  if (newX< 1 || world.isBlocked(new Point(newX, pos.y)))
                        {if ("" != null) return false;}
                  else
                        {if ("" != null) return true;}
      break;
      }
    default:
      jj_la1[28] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public boolean canJumpLRFBCondition(int steps) throws ParseException {Point pos;
  Point newPos;
  int newP;
  int cardinalDir;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LEFT:{
      jj_consume_token(LEFT);
pos=world.getPosition();
                  newPos= getNewPos( steps, "LEFT");

                  if (newPos.x==pos.x)
                        newP=newPos.y;
                  else
                        newP=newPos.x;

                  if (newP > world.getN() || newP<1  || world.isBlocked(newPos) )
                        {if ("" != null) return false;}
                  else
                        {if ("" != null) return true;}
      break;
      }
    case RIGHT:{
      jj_consume_token(RIGHT);
pos=world.getPosition();
                  newPos= getNewPos( steps, "RIGHT");

                  if (newPos.x==pos.x)
                        newP=newPos.y;
                  else
                        newP=newPos.x;

                  if (newP > world.getN() || newP<1 || world.isBlocked(newPos) )
                        {if ("" != null) return false;}
                  else
                        {if ("" != null) return true;}
      break;
      }
    case FRONT:{
      jj_consume_token(FRONT);
pos=world.getPosition();
                  newPos= getNewPos( steps, "FRONT");

                  if (newPos.x==pos.x)
                        newP=newPos.y;
                  else
                        newP=newPos.x;

                  if (newP > world.getN() || newP<1 || world.isBlocked(newPos) )
                        {if ("" != null) return false;}
                  else
                        {if ("" != null) return true;}
      break;
      }
    case BACK:{
      jj_consume_token(BACK);
pos=world.getPosition();
                  newPos= getNewPos( steps, "BACK");

                  if (newPos.x==pos.x)
                        newP=newPos.y;
                  else
                        newP=newPos.x;

                  if (newP > world.getN() || newP<1  || world.isBlocked(newPos) )
                        {if ("" != null) return false;}
                  else
                        {if ("" != null) return true;}
      break;
      }
    default:
      jj_la1[29] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public boolean canMoveNESWCondition(int steps) throws ParseException {Point pos;
  int newY;
  int newX;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SOUTH:{
      jj_consume_token(SOUTH);
pos=world.getPosition();
                  newY=pos.y+steps;
                  if (newY > world.getN() || world.blockedInRange(pos.x, pos.y, newY, SOUTH) || world.isBlocked(new Point(pos.x, newY)))
                        {if ("" != null) return false;}
                  else
                        {if ("" != null) return true;}
      break;
      }
    case NORTH:{
      jj_consume_token(NORTH);
pos=world.getPosition();
                  newY=pos.y- steps;
                  if (newY< 1 || world.blockedInRange(pos.x, pos.y, newY, NORTH) || world.isBlocked(new Point(pos.x, newY)))
                        {if ("" != null) return false;}
                  else
                        {if ("" != null) return true;}
      break;
      }
    case EAST:{
      jj_consume_token(EAST);
pos=world.getPosition();
                  newX=pos.x+ steps;
                  if (newX > world.getN() || world.blockedInRange(pos.x, pos.y, newX, EAST) || world.isBlocked(new Point(newX, pos.y)))
                        {if ("" != null) return false;}
                  else
                        {if ("" != null) return true;}
      break;
      }
    case WEST:{
      jj_consume_token(WEST);
pos=world.getPosition();
                  newX=pos.x- steps;
                  if (newX< 1 || world.blockedInRange(pos.x, pos.y, newX, WEST) || world.isBlocked(new Point(newX, pos.y)))
                        {if ("" != null) return false;}
                  else
                        {if ("" != null) return true;}
      break;
      }
    default:
      jj_la1[30] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public boolean canMoveLRFBCondition(int steps) throws ParseException {Point pos;
  Point newPos;
  int newP;
  int cardinalDir;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LEFT:{
      jj_consume_token(LEFT);
pos=world.getPosition();
                  newPos= getNewPos( steps, "LEFT");

                  if (newPos.x==pos.x)
                        newP=newPos.y;
                  else
                        newP=newPos.x;

                 cardinalDir= getCardinalDirHeaded("LEFT");

                  if (newP > world.getN() || newP<1 || world.blockedInRange(pos.x, pos.y, newP, cardinalDir) || world.isBlocked(newPos) )
                        {if ("" != null) return false;}
                  else
                        {if ("" != null) return true;}
      break;
      }
    case RIGHT:{
      jj_consume_token(RIGHT);
pos=world.getPosition();
                  newPos= getNewPos( steps, "RIGHT");

                  if (newPos.x==pos.x)
                        newP=newPos.y;
                  else
                        newP=newPos.x;

                 cardinalDir= getCardinalDirHeaded("RIGHT");

                  if (newP > world.getN() || newP<1 || world.blockedInRange(pos.x, pos.y, newP, cardinalDir) || world.isBlocked(newPos) )
                        {if ("" != null) return false;}
                  else
                        {if ("" != null) return true;}
      break;
      }
    case FRONT:{
      jj_consume_token(FRONT);
pos=world.getPosition();
                  newPos= getNewPos( steps, "FRONT");

                  if (newPos.x==pos.x)
                        newP=newPos.y;
                  else
                        newP=newPos.x;

                 cardinalDir= getCardinalDirHeaded("FRONT");

                  if (newP > world.getN() || newP<1 || world.blockedInRange(pos.x, pos.y, newP, cardinalDir) || world.isBlocked(newPos) )
                        {if ("" != null) return false;}
                  else
                        {if ("" != null) return true;}
      break;
      }
    case BACK:{
      jj_consume_token(BACK);
pos=world.getPosition();
                  newPos= getNewPos( steps, "BACK");

                  if (newPos.x==pos.x)
                        newP=newPos.y;
                  else
                        newP=newPos.x;

                 cardinalDir= getCardinalDirHeaded("BACK");

                  if (newP > world.getN() || newP<1 || world.blockedInRange(pos.x, pos.y, newP, cardinalDir) || world.isBlocked(newPos) )
                        {if ("" != null) return false;}
                  else
                        {if ("" != null) return true;}
      break;
      }
    default:
      jj_la1[31] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public boolean canMoveInDirToTheCondition(int x) throws ParseException {boolean bool;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INDIR:{
      jj_consume_token(INDIR);
      bool = canMoveNESWCondition(x);
{if ("" != null) return bool;}
      break;
      }
    case TOTHE:{
      jj_consume_token(TOTHE);
      bool = canMoveLRFBCondition(x);
{if ("" != null) return bool ;}
      break;
      }
    default:
      jj_la1[32] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public boolean canPutCondition(int x) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case BALLOONS:{
      jj_consume_token(BALLOONS);
if ( world.getMyBalloons()< x) {if ("" != null) return false;} else {if ("" != null) return true;}
      break;
      }
    case CHIPS:{
      jj_consume_token(CHIPS);
if (x > world.freeSpacesForChips() ||  world.getMyChips()< x) {if ("" != null) return false;} else {if ("" != null) return true;}
      break;
      }
    default:
      jj_la1[33] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public boolean canPickCondition(int x) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case BALLOONS:{
      jj_consume_token(BALLOONS);
if (x > world.countBalloons()) {if ("" != null) return false;} else {if ("" != null) return true;}
      break;
      }
    case CHIPS:{
      jj_consume_token(CHIPS);
if (x > world.chipsToPick()) {if ("" != null) return false;} else {if ("" != null) return true;}
      break;
      }
    default:
      jj_la1[34] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public boolean facingCondition() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NORTH:{
      jj_consume_token(NORTH);
{if ("" != null) return world.facingNorth();}
      break;
      }
    case SOUTH:{
      jj_consume_token(SOUTH);
{if ("" != null) return world.facingSouth();}
      break;
      }
    case EAST:{
      jj_consume_token(EAST);
{if ("" != null) return world.facingEast();}
      break;
      }
    case WEST:{
      jj_consume_token(WEST);
{if ("" != null) return world.facingWest();}
      break;
      }
    default:
      jj_la1[35] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

//
//OTROS
  final public int expr(String procName) throws ParseException {int total = 0;
    int valor;
    Token operador;
    valor = factor(procName);
total = valor;
{if ("" != null) return total;}
    throw new Error("Missing return statement in function");
}

  final public int factor(String procName) throws ParseException {int total = 0;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUM:{
      jj_consume_token(NUM);
total = Integer.parseInt(token.image); {if ("" != null) return total;}
      break;
      }
    case ID:{
      jj_consume_token(ID);
if (procName.equals(""))
        {
            if (!variables.containsKey(token.image))
            {
                {if (true) throw new Error("Variable global no definida: " + token.image);}
            }
            total = variables.get(token.image);
        }
        else
        {
            if (!procedures.containsKey(procName) )
            {
                {if (true) throw new Error("Variable '" + token.image + "' no definida en el procedimiento '" + procName + "'");}
            }
            else if (procedures.get(procName).paramNames.contains(token.image))
            {
              total=procedures.get(procName).paramValues.get(token.image);
                }
                else if (variables.containsKey(token.image))
            {
                total=variables.get(token.image);
            }
                else if (procedures.get(procName).varLocales.containsKey(token.image) )
                {
                  total=procedures.get(procName).varLocales.get(token.image);
            }
            else
            {
              {if (true) throw new Error("Variable '" + token.image + "' no definida en el procedimiento '" + procName + "'");}
                }
        }

        {if ("" != null) return total;}
      break;
      }
    default:
      jj_la1[36] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

//
//FACING RELATED
  final public void changeFace(int dir) throws ParseException {
while (world.getFacing()!=dir)
                world.turnRight();
}

  final public void faceDirections(boolean ejecutar, int numVeces, String procName) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case WEST:{
      jj_consume_token(WEST);
if (ejecutar)
                                { for (int i = 0; i < numVeces; i++)
                                        { changeFace(3); }
                                }
                                if (procedures.containsKey(procName) ){
                                Procedure proc= procedures.get(procName);
                                proc.body.add("face west_"); }
      break;
      }
    case EAST:{
      jj_consume_token(EAST);
if (ejecutar)
                                { for (int i = 0; i < numVeces; i++)
                                        { changeFace(2); }
                                }
                                if (procedures.containsKey(procName) ){
                                Procedure proc= procedures.get(procName);
                                proc.body.add("face east_"); }
      break;
      }
    case NORTH:{
      jj_consume_token(NORTH);
if (ejecutar)
                                { for (int i = 0; i < numVeces; i++)
                                        { changeFace(0); }
                                }
                                if (procedures.containsKey(procName) ){
                                Procedure proc= procedures.get(procName);
                                proc.body.add("face north_"); }
      break;
      }
    case SOUTH:{
      jj_consume_token(SOUTH);
if (ejecutar)
                                { for (int i = 0; i < numVeces; i++)
                                        { changeFace(1); }
                                }
                                if (procedures.containsKey(procName) ){
                                Procedure proc= procedures.get(procName);
                                proc.body.add("face south_"); }
      break;
      }
    default:
      jj_la1[37] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void turnDirections(boolean ejecutar, int numVeces, String procName) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case RIGHT:{
      jj_consume_token(RIGHT);
if (ejecutar) world.turnRight();
                                if (procedures.containsKey(procName) ){
                                Procedure proc= procedures.get(procName);
                                proc.body.add("turn right_"); }
      break;
      }
    case LEFT:{
      jj_consume_token(LEFT);
if (ejecutar)
                        { for (int i = 0; i < numVeces; i++)
                        { world.turnRight();
                        world.turnRight();
                        world.turnRight();}
                  }
                        if (procedures.containsKey(procName) ){
                        Procedure proc= procedures.get(procName);
                        proc.body.add("turn left_"); }
      break;
      }
    case AROUND:{
      jj_consume_token(AROUND);
if (ejecutar)
                        { for (int i = 0; i < numVeces; i++)
                        { world.turnRight();
                         world.turnRight(); }
                        }

                        if (procedures.containsKey(procName) ){
                        Procedure proc= procedures.get(procName);
                        proc.body.add("turn around_"); }
      break;
      }
    default:
      jj_la1[38] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

//
//AUXILIARES
//
  final public int getCardinalDirHeaded(String dir) throws ParseException {int facing;
facing=world.getFacing();
  if (dir=="FRONT")
        {if ("" != null) return world.getFacing();}

  else if (dir=="BACK")
  {
        if (facing==0)
                {if ("" != null) return 1;}
        else if (facing==1)
                {if ("" != null) return 0;}
        else if (facing==2)
                {if ("" != null) return 3;}
        else
                {if ("" != null) return 2;}
  }

  else if (dir=="LEFT")
  {
        if (facing==0)
                {if ("" != null) return 3;}
        else if (facing==1)
                {if ("" != null) return 2;}
        else if (facing==2)
                {if ("" != null) return 1;}
        else
                {if ("" != null) return 0;}

  }

  else
  {
        if (facing==0)
                {if ("" != null) return 2;}
        else if (facing==1)
                {if ("" != null) return 3;}
        else if (facing==2)
                {if ("" != null) return 0;}
        else
                {if ("" != null) return 1;}

  }
    throw new Error("Missing return statement in function");
}

  final public Point getNewPos(int steps, String dir) throws ParseException {
Point newPos= new Point(1,1);
  Point oldPos= world.getPosition();
  int facing = world.getFacing();

  if (dir=="FRONT")
  {
        if (facing==0)
                newPos= new Point (oldPos.x, oldPos.y-steps);
        else if (facing==1)
                newPos=new Point (oldPos.x, oldPos.y+steps);
        else if (facing==2)
                newPos=new Point (oldPos.x+steps, oldPos.y);
        else if (facing==3)
                newPos=new Point (oldPos.x-steps, oldPos.y);

  }

  else if (dir=="BACK")
  {
        if (facing==0)
                newPos= new Point (oldPos.x, oldPos.y+steps);
        else if (facing==1)
                newPos=new Point (oldPos.x, oldPos.y-steps);
        else if (facing==2)
                newPos=new Point (oldPos.x-steps, oldPos.y);
        else if (facing==3)
                newPos=new Point (oldPos.x+steps, oldPos.y);

  }

  else if (dir=="LEFT")
  {
        if (facing==0)
                newPos= new Point (oldPos.x-steps, oldPos.y);
        else if (facing==1)
                newPos=new Point (oldPos.x+steps, oldPos.y);
        else if (facing==2)
                newPos=new Point (oldPos.x, oldPos.y+steps);
        else if (facing==3)
                newPos=new Point (oldPos.x, oldPos.y-steps);

  }

  else
  {
        if (facing==0)
                newPos= new Point (oldPos.x+steps, oldPos.y);
        else if (facing==1)
                newPos=new Point (oldPos.x-steps, oldPos.y);
        else if (facing==2)
                newPos=new Point (oldPos.x, oldPos.y-steps);
        else if (facing==3)
                newPos=new Point (oldPos.x, oldPos.y+steps);

  }

  {if ("" != null) return newPos;}
    throw new Error("Missing return statement in function");
}

//
//BODY PROCEDURE Y WHILE INTERPRETER
  final public void procBodyCommands(String procName) throws ParseException {Procedure proc=procedures.get(procName);
  List<String > body = proc.body;
  String[] instrArr;
  int num;
for (int i = 0; i < body.size(); i++)
          {
            instrArr=body.get(i).split("_");

            if (instrArr[0].equals("move forward"))
                { num=Integer.parseInt(instrArr[1]);
                  world.moveForward(num, false); }
            else if (instrArr[0].equals("move north"))
                { num=Integer.parseInt(instrArr[1]);
                instrMoveNorth(num);}
            else if (instrArr[0].equals("move south"))
                { num=Integer.parseInt(instrArr[1]);
                instrMoveSouth(num);}
            else if (instrArr[0].equals("move west"))
                { num=Integer.parseInt(instrArr[1]);
                instrMoveWest(num);}
            else if (instrArr[0].equals("move east"))
                { num=Integer.parseInt(instrArr[1]);
                instrMoveEast(num);}
            else if (instrArr[0].equals("move back"))
                { num=Integer.parseInt(instrArr[1]);
                instrMoveJumpBack(num, false);}
            else if (instrArr[0].equals("move left"))
                { num=Integer.parseInt(instrArr[1]);
                instrMoveJumpLeft(num, false);}
            else if (instrArr[0].equals("move right"))
                { num=Integer.parseInt(instrArr[1]);
                instrMoveJumpRight(num, false);}

            else if (instrArr[0].equals("jump forward"))
                { num=Integer.parseInt(instrArr[1]);
                  world.moveForward(num, true); }
            else if (instrArr[0].equals("jump north"))
                { num=Integer.parseInt(instrArr[1]);
                instrJumpNorth(num);}
            else if (instrArr[0].equals("jump south"))
                { num=Integer.parseInt(instrArr[1]);
                instrJumpSouth(num);}
            else if (instrArr[0].equals("jump west"))
                { num=Integer.parseInt(instrArr[1]);
                instrJumpWest(num);}
            else if (instrArr[0].equals("jump east"))
                { num=Integer.parseInt(instrArr[1]);
                instrJumpEast(num);}
            else if (instrArr[0].equals("jump back"))
                {num=Integer.parseInt(instrArr[1]);
                instrMoveJumpBack(num, true);}
            else if (instrArr[0].equals("jump left"))
                { num=Integer.parseInt(instrArr[1]);
                instrMoveJumpLeft(num, true);}
            else if (instrArr[0].equals("jump right"))
                { num=Integer.parseInt(instrArr[1]);
                instrMoveJumpRight(num, true);}

           else if (instrArr[0].equals("turn right"))
                { world.turnRight();}
            else if (instrArr[0].equals("turn around"))
                { world.turnRight();
                world.turnRight();}
            else if (instrArr[0].equals("turn left"))
                { world.turnRight();
                world.turnRight();
                world.turnRight();}

            else if (instrArr[0].equals("face north"))
                { changeFace(0);}
            else if (instrArr[0].equals("face south"))
                { changeFace(1);}
            else if (instrArr[0].equals("face west"))
                { changeFace(3);}
            else if (instrArr[0].equals("face east"))
                { changeFace(2);}
          }
}

//Move instr
  final public void instrMoveNorth(int x) throws ParseException {
world.moveVertically(-x, false);
        changeFace(0);
}

  final public void instrMoveSouth(int x) throws ParseException {
world.moveVertically(x, false);
        changeFace(1);
}

  final public void instrMoveWest(int x) throws ParseException {
world.moveHorizontally(-x, false);
        changeFace(3);
}

  final public void instrMoveEast(int x) throws ParseException {
world.moveHorizontally(x, false);
        changeFace(2);
}

//Jump instr
  final public void instrJumpNorth(int x) throws ParseException {
world.moveVertically(-x, true);
        changeFace(0);
}

  final public void instrJumpSouth(int x) throws ParseException {
world.moveVertically(x, true);
        changeFace(1);
}

  final public void instrJumpWest(int x) throws ParseException {
world.moveHorizontally(-x, true);
        changeFace(3);
}

  final public void instrJumpEast(int x) throws ParseException {
world.moveHorizontally(x, true);
        changeFace(2);
}

  final public void instrMoveJumpLeft(int x, boolean bool) throws ParseException {
if (world.getFacing()==0)
        world.moveHorizontally(-x, bool) ;
  else if (world.getFacing()==1)
        world.moveHorizontally(x, bool) ;
  else if (world.getFacing()==2)
        world.moveVertically(-x, bool) ;
  else
        world.moveVertically(x, bool) ;
}

  final public void instrMoveJumpRight(int x, boolean bool) throws ParseException {
if (world.getFacing()==0)
        world.moveHorizontally(x, bool) ;
  else if (world.getFacing()==1)
        world.moveHorizontally(-x, bool) ;
  else if (world.getFacing()==2)
        world.moveVertically(x, bool) ;
  else
        world.moveVertically(-x, bool) ;
}

  final public void instrMoveJumpBack(int x, boolean bool) throws ParseException {
if (world.getFacing()==0)
        world.moveVertically(x, bool) ;
  else if (world.getFacing()==1)
  world.moveVertically(-x, bool) ;
  else if (world.getFacing()==2)
        world.moveHorizontally(-x, bool) ;
  else
        world.moveHorizontally(x, bool) ;
}

  /** Generated Token Manager. */
  public RobotTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[39];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x0,0x4297be01,0x4297be00,0x4297be01,0x40000000,0x0,0x0,0x4297be01,0x40000000,0x40000000,0x80000,0x40000000,0x0,0x0,0x0,0xc000000,0xc000000,0x0,0x0,0x4297be01,0x4297be01,0x400000,0x4297be01,0x4297be01,0x2800000,0x0,0x0,0xc000000,0x0,0x0,0x0,0x0,0xc000000,0x0,0x0,0x0,0x40000000,0x0,0x0,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x3,0x800000,0x0,0x0,0x0,0x100000,0x800000,0x0,0x400000,0x400000,0x300000,0x0,0x300000,0x3c,0x780,0x0,0x0,0x780,0x3c,0x0,0x0,0x0,0x0,0x0,0x0,0x80000,0x7c000,0x0,0x780,0x3c,0x780,0x3c,0x0,0x3,0x3,0x780,0x2000,0x780,0x70,};
	}

  /** Constructor with InputStream. */
  public Robot(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Robot(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new RobotTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 39; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 39; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Robot(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new RobotTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 39; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new RobotTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 39; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Robot(RobotTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 39; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(RobotTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 39; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[58];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 39; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 58; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
